server:
  port: 8081

spring:
  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    name: notification-service

admin:
  emails:
    - "kss200486@gmail.com"
    - "kiss200486@mail.ru"

springdoc:
  swagger-ui:
    path: /swagger-ui.html
